
apiVersion: apps/v1

kind: Deployment

metadata:

      name: rogerdev-blogspot-backend-deployment

spec:

  replicas: 3

  selector:

    matchLabels:

      app: rogerdev-blogspot-backend

  strategy:

    type: Recreate

  template:

    metadata:

      labels:

        app: rogerdev-blogspot-backend

    spec:

      containers:

      - name: rogerdev-blogspot-backend

        image: mawan1122/rogerdev-blogspot-backend:latest

        envFrom:

          - secretRef:

              name: rogerdev-blogspot-db-secret

        ports:

           - containerPort: 8081
---

apiVersion: v1

kind: Service

metadata:

  name: rogerdev-blogspot-backend-service

spec:

  selector:

    app: rogerdev-blogspot-backend

  ports:

    - port: 8080

      targetPort: 8081
 
# ---

# apiVersion: networking.k8s.io/v1

# kind: Ingress

# metadata:

#   name: rogerdev-blogspot-backend-ingress

#   annotations:

#       nginx.ingress.kubernetes.io/rewrite-target: /
# spec:

#   rules:

#     - host: rogerdev.mawan.info

#       http:

#         paths:

#           - path: /

#             pathType: Prefix

#             backend:

#               service:

#                 name: rogerdev-blogspot-backend-service
#                 port:

#                   number: 8080
          